version: '3'
services:
  rendertron:
    image: terillos/rendertron
    ports:
    - "9050:3000"
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - rendertron
    environment:
      - BOT_TOKEN=2054038321:AAHrWbcc99iRFT2DMZan33hyOzfhCNwQqK4
